### PR TITLE
(bugfix/issue-55) Support non-string based ids for gremlin connector

### PR DESCRIPTION
**Pull request by nestoralvarezd**
Issue #55

#### Description of changes:
- Updates Gremlin connector to take into account non-string based ids for nodes and edges during the mapping

#### How Has This Been Tested?
- Mount a local instance of Tinkerpop `docker run --rm -p 8182:8182 tinkerpop/gremlin-server conf/gremlin-server-rest-modern.yaml` using the REST configuration. The default graph contains vertices of type person and software whose ids are like `{"@type":"g:Int64","@value":1}`. These kind of non-string ids are the reason of the issue.
- Create a new configuration with the following parameters:
  - Public endpoint: http://localhost:8182
  - Enable cache: false (only to guarantee that all the requests are always performed against the database)

- After synchronization, inspect the 4 people of the 2 software in the connection details
- "Node id" column now is not `[Object object]` but it shows the numeric value of the id.
- It has also been checked that this change does not affect to search or expand capabilities.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by triggan** [comment]
This seems to be fetching the IDs as numerics now and pulling them into the tabular view of all vertices.  However, I'm now seeing an issue where fetching a vertex into the Explorer UI and attempting to expand it is not working correctly.

I'm testing with the following test graph in Gremlin Server [1]:

```
g.addV('testV').
as('1').
addV('testV').
as('2').
addE('testE').from('1').to('2')
```

Going into the tabular view of all vertices, I can select one of the two "testV' vertices and bring it into the Explorer UI successfully.  When I go to expand the vertex to look for neighbors via double-clicking the vertex, the UI states that there are no neighbor vertices.  After reviewing the Dev Tools Network tab, I noticed that we're generating the following query:

```
g.V("42774").both().dedup().group().by(label).by(count())
```

So the UI is attempting to fetch a vertex with the ID as a String instead of with a Long. The query should be:

```
g.V(42774L).both().dedup().group().by(label).by(count())
```

[1] Note that I'm allowing Gremlin Server to generate IDs for me and the default is to generate IDs as Longs.

**Review by krlawrence — CHANGES_REQUESTED** [review]
Please see comments from @triggan

**Comment by krlawrence** [comment]
I built a version of the Explorer with this PR included. It helped with the issues reported in #33 (Explorer not working with JanusGraph - which also uses numeric IDs).  The Explorer will now display nodes. However, when I expand a node, existing (displayed) edges get hidden.

**Comment by nalvarezdiaz** [comment]
> This seems to be fetching the IDs as numerics now and pulling them into the tabular view of all vertices. However, I'm now seeing an issue where fetching a vertex into the Explorer UI and attempting to expand it is not working correctly.
> 
> I'm testing with the following test graph in Gremlin Server [1]:
> 
> ```
> g.addV('testV').
> as('1').
> addV('testV').
> as('2').
> addE('testE').from('1').to('2')
> ```
> 
> Going into the tabular view of all vertices, I can select one of the two "testV' vertices and bring it into the Explorer UI successfully. When I go to expand the vertex to look for neighbors via double-clicking the vertex, the UI states that there are no neighbor vertices. After reviewing the Dev Tools Network tab, I noticed that we're generating the following query:
> 
> ```
> g.V("42774").both().dedup().group().by(label).by(count())
> ```
> 
> So the UI is attempting to fetch a vertex with the ID as a String instead of with a Long. The query should be:
> 
> ```
> g.V(42774L).both().dedup().group().by(label).by(count())
> ```
> 
> [1] Note that I'm allowing Gremlin Server to generate IDs for me and the default is to generate IDs as Longs.

I've updated the PR to properly manage numeric ids. Now, we store the id type inside the GremlinConnector to be able to differentiate string based ids from numeric ids and fetch neighbors using the corresponding template.

**Comment by krlawrence** [comment]
I think it's OK to fix it in a separate PR, but a Gremlin Server also allows UUIDs to be used as the ID type. I added a comment about this in issue #55

**Comment by krlawrence** [comment]
I built the latest code with this PR included. I'm still seeing issues.
1. When you expand an edge, other already expanded edges vanish.
2. When you add a node and expand it (starting with a clear canvas) the 2 nodes briefly appear nicely with their edge shown but then immediately collapse on top of each other. I reported this above and it remains a problem.

**Comment by krlawrence** [comment]
I built a new container image, and retested with the latest commits. The nodes not expanding correctly when first rendered issue (in Firefox) seems to be improved now. However, every layout seems to run twice now which looks a little odd to a user. The edges vanishing when the Explorer is connected to Janus Graph also seems fixed now. I also tested with Neptune.

**Comment by krlawrence** [comment]
I built and tested with the latest fixes and the double redraw issue is now resolved. I tested on Firefox and Chrome. I think this PR can now be merged.

**Review by krlawrence — APPROVED** [review]
Latest updates seem to have resolved the remaining issues called out in the comments.

**Pull request merged**
