### PR TITLE
Add Match Precision option to keyword search

### PR DESCRIPTION
**Pull request by michaelnchin**
Issue #, if available: #149

Description of changes:
- Added a new `Match Precision` drop-down field to the keyword search interface. Users can now choose to match using options:
  - a) `Exact`: Node must have an attribute value that matches the search keyword exactly. 
  - b) `Partial`: Node has an attribute value containing the search keyword. This option is identical to the old search behavior, and will remain as the default option.

Example usage:
- EDIT: `Fuzzy` option has been renamed to `Partial`.
Screen Shot 2023-08-21 at 7 34 10 PM

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by cubeddu — APPROVED** [review]
LGTM @michaelnchin Thanks!

**Review by cubeddu — DISMISSED** [review]

**Comment by cubeddu** [comment]
@michaelnchin connector/gremlin/templates/keywordSearchTemplate.test.ts a few test are failing now.

**Comment by michaelnchin** [comment]
@cubeddu Thank you for the heads up - fixed and added extra tests.

**Review by cubeddu — APPROVED** [review]
LGTM

**Pull request merged**
